policy_id: rsl_rl_lift_object_official
type: rsl_rl
policy_config_dict:
  checkpoint_path: "/workspace/isaaclab_arena/isaaclab_arena/tests/test_data/lift_object_model.pt"
  device: "cuda:0"
strength: 1.0
memory_bonus: 0.0
